apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: onboarding-metrics
  name: onboarding-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onboarding-metrics
  template:
    metadata:
      labels:
        app: onboarding-metrics
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '3000'
    spec:
      containers:
        - image: saloniv/onboarding-metrics
          name: saloniv/onboarding-metrics
          ports:
            - containerPort: 3000